language: rust
sudo: required
cache: cargo

addons:
  apt:
    packages:
      - libzstd-dev

before_install:
  - set -e
  - rustup self update

script:
  - cargo build --all
  - cargo test --all --no-fail-fast -- --test-threads=1
