[package]
name = "binance"
description = "Binance exange market data ingestor"
version = "0.1.0"
authors = ["jetTeam"]
publish = false
license = "GPL-3.0"
readme = "README.md"

[dependencies]
common = { path = "../common"}
tokio-tungstenite = "0.9"
tokio = "0.1"
futures = "0.1"
url = "2.1"
